### ISSUE TITLE
Deploy not working

### ISSUE THREAD

**Issue by svarughese91** [serverless/github-action#40]
My serverless deploy to AWS was working fine this morning and now all of a sudden its failing and throwing this error:

Serverless: Publishing service to the Serverless Dashboard...
TypeError: Cannot read property 'fetch' of undefined
    at parseDeploymentData (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/deployment/parse.js:159:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 
  Type Error ---------------------------------------------
 
  TypeError: Cannot read property 'fetch' of undefined
      at parseDeploymentData (/opt/hostedtoolcache/node/10.22.0/x64/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/deployment/parse.js:159:65)
      at process._tickCallback (internal/process/next_tick.js:68:7)

Do you know whats wrong?

**Comment by Gdewilde** [comment]
Hi, you need to upgrade serverless to 3.1.1

**Comment by svarughese91** [comment]
@Gdewilde isnt the latest version of serverless 2.1.1?  https://www.npmjs.com/package/serverless

**Comment by Gdewilde** [comment]
Yes, sorry about that 😅

**Comment by DavideViolante** [comment]
it should be fixed now.
